// Code generated by MockGen. DO NOT EDIT.
// Source: file.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source file.go -destination provider_mock_test.go -package fileresource
//

// Package fileresource is a generated GoMock package.
package fileresource

import (
	context "context"
	reflect "reflect"

	model "github.com/choria-io/ccm/model"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source file.go -destination provider_mock_test.go -package fileresource

// MockFileProvider is a mock of FileProvider interface.
type MockFileProvider struct {
	ctrl     *gomock.Controller
	recorder *MockFileProviderMockRecorder
	isgomock struct{}
}

// MockFileProviderMockRecorder is the mock recorder for MockFileProvider.
type MockFileProviderMockRecorder struct {
	mock *MockFileProvider
}

// NewMockFileProvider creates a new mock instance.
func NewMockFileProvider(ctrl *gomock.Controller) *MockFileProvider {
	mock := &MockFileProvider{ctrl: ctrl}
	mock.recorder = &MockFileProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileProvider) EXPECT() *MockFileProviderMockRecorder {
	return m.recorder
}

// CreateDirectory mocks base method.
func (m *MockFileProvider) CreateDirectory(ctx context.Context, dir, owner, group, mode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDirectory", ctx, dir, owner, group, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDirectory indicates an expected call of CreateDirectory.
func (mr *MockFileProviderMockRecorder) CreateDirectory(ctx, dir, owner, group, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDirectory", reflect.TypeOf((*MockFileProvider)(nil).CreateDirectory), ctx, dir, owner, group, mode)
}

// Name mocks base method.
func (m *MockFileProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockFileProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockFileProvider)(nil).Name))
}

// Status mocks base method.
func (m *MockFileProvider) Status(ctx context.Context, file string) (*model.FileState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, file)
	ret0, _ := ret[0].(*model.FileState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockFileProviderMockRecorder) Status(ctx, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockFileProvider)(nil).Status), ctx, file)
}

// Store mocks base method.
func (m *MockFileProvider) Store(ctx context.Context, file string, contents []byte, source, owner, group, mode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, file, contents, source, owner, group, mode)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockFileProviderMockRecorder) Store(ctx, file, contents, source, owner, group, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockFileProvider)(nil).Store), ctx, file, contents, source, owner, group, mode)
}
