// Code generated by MockGen. DO NOT EDIT.
// Source: resources/scaffold/scaffold.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source resources/scaffold/scaffold.go -destination resources/scaffold/provider_mock_test.go -package scaffoldresource
//

// Package scaffoldresource is a generated GoMock package.
package scaffoldresource

import (
	context "context"
	reflect "reflect"

	model "github.com/choria-io/ccm/model"
	templates "github.com/choria-io/ccm/templates"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source resources/scaffold/scaffold.go -destination resources/scaffold/provider_mock_test.go -package scaffoldresource

// MockScaffoldProvider is a mock of ScaffoldProvider interface.
type MockScaffoldProvider struct {
	ctrl     *gomock.Controller
	recorder *MockScaffoldProviderMockRecorder
	isgomock struct{}
}

// MockScaffoldProviderMockRecorder is the mock recorder for MockScaffoldProvider.
type MockScaffoldProviderMockRecorder struct {
	mock *MockScaffoldProvider
}

// NewMockScaffoldProvider creates a new mock instance.
func NewMockScaffoldProvider(ctrl *gomock.Controller) *MockScaffoldProvider {
	mock := &MockScaffoldProvider{ctrl: ctrl}
	mock.recorder = &MockScaffoldProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScaffoldProvider) EXPECT() *MockScaffoldProviderMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockScaffoldProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockScaffoldProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockScaffoldProvider)(nil).Name))
}

// Remove mocks base method.
func (m *MockScaffoldProvider) Remove(ctx context.Context, prop *model.ScaffoldResourceProperties, state *model.ScaffoldState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, prop, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockScaffoldProviderMockRecorder) Remove(ctx, prop, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockScaffoldProvider)(nil).Remove), ctx, prop, state)
}

// Scaffold mocks base method.
func (m *MockScaffoldProvider) Scaffold(ctx context.Context, env *templates.Env, prop *model.ScaffoldResourceProperties, noop bool) (*model.ScaffoldState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scaffold", ctx, env, prop, noop)
	ret0, _ := ret[0].(*model.ScaffoldState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Scaffold indicates an expected call of Scaffold.
func (mr *MockScaffoldProviderMockRecorder) Scaffold(ctx, env, prop, noop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scaffold", reflect.TypeOf((*MockScaffoldProvider)(nil).Scaffold), ctx, env, prop, noop)
}

// Status mocks base method.
func (m *MockScaffoldProvider) Status(ctx context.Context, env *templates.Env, prop *model.ScaffoldResourceProperties) (*model.ScaffoldState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, env, prop)
	ret0, _ := ret[0].(*model.ScaffoldState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockScaffoldProviderMockRecorder) Status(ctx, env, prop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockScaffoldProvider)(nil).Status), ctx, env, prop)
}
