version: 2
project_name: ccm

release:
  github:
    owner: choria-io
    name: ccm
  name_template: "Release {{.Version}}"
  draft: true

changelog:
  disable: true

builds:
  - id: ccm
    main: ./cmd
    binary: ccm
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    goarm:
      - "6"
      - "7"

archives:
  - name_template: "ccm-{{.Version}}-{{.Os}}-{{.Arch}}{{if .Arm}}{{.Arm}}{{end}}"
    wrap_in_directory: true
    formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - README.md
      - LICENSE
      - src: build/ccm-agent.service
        dst: ccm-agent.service
      - src: build/agent.yaml
        dst: agent.yaml

homebrew_casks:
  - name: ccm
    directory: Formula
    repository:
      owner: choria-io
      name: homebrew-tap
    url:
      template: "https://github.com/choria-io/ccm/releases/download/{{ .Tag }}/ccm-{{.Version}}-{{ .Os }}-{{ .Arch }}{{if .Arm}}{{.Arm}}{{end}}.tar.gz"
    homepage: "https://github.com/choria-io/ccm"
    description: "Choria Configuration Management"
    skip_upload: false

nfpms:
  - package_name: ccm
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: Choria.IO
    homepage: http://choria-io.github.io/ccm/
    maintainer: R.I.Pienaar <rip@choria.io>
    description: Choria Configuration Management
    license: Apache 2.0
    bindir: /usr/bin
    epoch: 1
    version_metadata: git
    mtime: "{{ .CommitDate }}"
    contents:
      - src: build/ccm-agent.service
        dst: /lib/systemd/system/ccm-agent.service
      - dst: /etc/choria/ccm
        type: dir
        file_info:
          mode: 0755
      - src: build/agent.yaml
        dst: /etc/choria/ccm/agent.yaml
        type: config

    formats:
      - rpm
      - deb

checksum:
  name_template: "SHA256SUMS"
  algorithm: sha256
