// Code generated by MockGen. DO NOT EDIT.
// Source: resources/archive/archive.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source resources/archive/archive.go -destination resources/archive/provider_mock_test.go -package archiveresource
//

// Package archiveresource is a generated GoMock package.
package archiveresource

import (
	context "context"
	reflect "reflect"

	model "github.com/choria-io/ccm/model"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source resources/archive/archive.go -destination resources/archive/provider_mock_test.go -package archiveresource

// MockArchiveFactory is a mock of ArchiveFactory interface.
type MockArchiveFactory struct {
	ctrl     *gomock.Controller
	recorder *MockArchiveFactoryMockRecorder
	isgomock struct{}
}

// MockArchiveFactoryMockRecorder is the mock recorder for MockArchiveFactory.
type MockArchiveFactoryMockRecorder struct {
	mock *MockArchiveFactory
}

// NewMockArchiveFactory creates a new mock instance.
func NewMockArchiveFactory(ctrl *gomock.Controller) *MockArchiveFactory {
	mock := &MockArchiveFactory{ctrl: ctrl}
	mock.recorder = &MockArchiveFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArchiveFactory) EXPECT() *MockArchiveFactoryMockRecorder {
	return m.recorder
}

// IsManageable mocks base method.
func (m *MockArchiveFactory) IsManageable(arg0 map[string]any, arg1 model.ResourceProperties) (bool, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsManageable", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IsManageable indicates an expected call of IsManageable.
func (mr *MockArchiveFactoryMockRecorder) IsManageable(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsManageable", reflect.TypeOf((*MockArchiveFactory)(nil).IsManageable), arg0, arg1)
}

// Name mocks base method.
func (m *MockArchiveFactory) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockArchiveFactoryMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockArchiveFactory)(nil).Name))
}

// New mocks base method.
func (m *MockArchiveFactory) New(arg0 model.Logger, arg1 model.CommandRunner) (model.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", arg0, arg1)
	ret0, _ := ret[0].(model.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockArchiveFactoryMockRecorder) New(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockArchiveFactory)(nil).New), arg0, arg1)
}

// TypeName mocks base method.
func (m *MockArchiveFactory) TypeName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TypeName")
	ret0, _ := ret[0].(string)
	return ret0
}

// TypeName indicates an expected call of TypeName.
func (mr *MockArchiveFactoryMockRecorder) TypeName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TypeName", reflect.TypeOf((*MockArchiveFactory)(nil).TypeName))
}

// MockArchiveProvider is a mock of ArchiveProvider interface.
type MockArchiveProvider struct {
	ctrl     *gomock.Controller
	recorder *MockArchiveProviderMockRecorder
	isgomock struct{}
}

// MockArchiveProviderMockRecorder is the mock recorder for MockArchiveProvider.
type MockArchiveProviderMockRecorder struct {
	mock *MockArchiveProvider
}

// NewMockArchiveProvider creates a new mock instance.
func NewMockArchiveProvider(ctrl *gomock.Controller) *MockArchiveProvider {
	mock := &MockArchiveProvider{ctrl: ctrl}
	mock.recorder = &MockArchiveProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArchiveProvider) EXPECT() *MockArchiveProviderMockRecorder {
	return m.recorder
}

// Download mocks base method.
func (m *MockArchiveProvider) Download(ctx context.Context, properties *model.ArchiveResourceProperties, log model.Logger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, properties, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Download indicates an expected call of Download.
func (mr *MockArchiveProviderMockRecorder) Download(ctx, properties, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockArchiveProvider)(nil).Download), ctx, properties, log)
}

// Extract mocks base method.
func (m *MockArchiveProvider) Extract(ctx context.Context, properties *model.ArchiveResourceProperties, log model.Logger) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extract", ctx, properties, log)
	ret0, _ := ret[0].(error)
	return ret0
}

// Extract indicates an expected call of Extract.
func (mr *MockArchiveProviderMockRecorder) Extract(ctx, properties, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extract", reflect.TypeOf((*MockArchiveProvider)(nil).Extract), ctx, properties, log)
}

// Name mocks base method.
func (m *MockArchiveProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockArchiveProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockArchiveProvider)(nil).Name))
}

// Status mocks base method.
func (m *MockArchiveProvider) Status(ctx context.Context, properties *model.ArchiveResourceProperties) (*model.ArchiveState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, properties)
	ret0, _ := ret[0].(*model.ArchiveState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockArchiveProviderMockRecorder) Status(ctx, properties any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockArchiveProvider)(nil).Status), ctx, properties)
}
