// Code generated by MockGen. DO NOT EDIT.
// Source: resources/applyresource/applyresource.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source resources/applyresource/applyresource.go -destination resources/applyresource/provider_mock_test.go -package applyresource
//

// Package applyresource is a generated GoMock package.
package applyresource

import (
	context "context"
	reflect "reflect"

	model "github.com/choria-io/ccm/model"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source resources/applyresource/applyresource.go -destination resources/applyresource/provider_mock_test.go -package applyresource

// MockApplyProvider is a mock of ApplyProvider interface.
type MockApplyProvider struct {
	ctrl     *gomock.Controller
	recorder *MockApplyProviderMockRecorder
	isgomock struct{}
}

// MockApplyProviderMockRecorder is the mock recorder for MockApplyProvider.
type MockApplyProviderMockRecorder struct {
	mock *MockApplyProvider
}

// NewMockApplyProvider creates a new mock instance.
func NewMockApplyProvider(ctrl *gomock.Controller) *MockApplyProvider {
	mock := &MockApplyProvider{ctrl: ctrl}
	mock.recorder = &MockApplyProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplyProvider) EXPECT() *MockApplyProviderMockRecorder {
	return m.recorder
}

// ApplyManifest mocks base method.
func (m *MockApplyProvider) ApplyManifest(ctx context.Context, mgr model.Manager, properties *model.ApplyResourceProperties, currentDepth int, healthCheckOnly bool, log model.Logger) (*model.ApplyState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyManifest", ctx, mgr, properties, currentDepth, healthCheckOnly, log)
	ret0, _ := ret[0].(*model.ApplyState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyManifest indicates an expected call of ApplyManifest.
func (mr *MockApplyProviderMockRecorder) ApplyManifest(ctx, mgr, properties, currentDepth, healthCheckOnly, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyManifest", reflect.TypeOf((*MockApplyProvider)(nil).ApplyManifest), ctx, mgr, properties, currentDepth, healthCheckOnly, log)
}

// Name mocks base method.
func (m *MockApplyProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockApplyProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockApplyProvider)(nil).Name))
}

// Status mocks base method.
func (m *MockApplyProvider) Status(ctx context.Context, properties *model.ApplyResourceProperties) (*model.ApplyState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, properties)
	ret0, _ := ret[0].(*model.ApplyState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockApplyProviderMockRecorder) Status(ctx, properties any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockApplyProvider)(nil).Status), ctx, properties)
}
