// Code generated by MockGen. DO NOT EDIT.
// Source: resources/base/base.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source resources/base/base.go -destination resources/base/embedded_mock_test.go -package base
//

// Package base is a generated GoMock package.
package base

import (
	context "context"
	reflect "reflect"

	model "github.com/choria-io/ccm/model"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source resources/base/base.go -destination resources/base/embedded_mock_test.go -package base

// MockEmbeddedResource is a mock of EmbeddedResource interface.
type MockEmbeddedResource struct {
	ctrl     *gomock.Controller
	recorder *MockEmbeddedResourceMockRecorder
	isgomock struct{}
}

// MockEmbeddedResourceMockRecorder is the mock recorder for MockEmbeddedResource.
type MockEmbeddedResourceMockRecorder struct {
	mock *MockEmbeddedResource
}

// NewMockEmbeddedResource creates a new mock instance.
func NewMockEmbeddedResource(ctrl *gomock.Controller) *MockEmbeddedResource {
	mock := &MockEmbeddedResource{ctrl: ctrl}
	mock.recorder = &MockEmbeddedResourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmbeddedResource) EXPECT() *MockEmbeddedResourceMockRecorder {
	return m.recorder
}

// ApplyResource mocks base method.
func (m *MockEmbeddedResource) ApplyResource(ctx context.Context) (model.ResourceState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyResource", ctx)
	ret0, _ := ret[0].(model.ResourceState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ApplyResource indicates an expected call of ApplyResource.
func (mr *MockEmbeddedResourceMockRecorder) ApplyResource(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyResource", reflect.TypeOf((*MockEmbeddedResource)(nil).ApplyResource), ctx)
}

// NewTransactionEvent mocks base method.
func (m *MockEmbeddedResource) NewTransactionEvent() *model.TransactionEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewTransactionEvent")
	ret0, _ := ret[0].(*model.TransactionEvent)
	return ret0
}

// NewTransactionEvent indicates an expected call of NewTransactionEvent.
func (mr *MockEmbeddedResourceMockRecorder) NewTransactionEvent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewTransactionEvent", reflect.TypeOf((*MockEmbeddedResource)(nil).NewTransactionEvent))
}

// SelectProvider mocks base method.
func (m *MockEmbeddedResource) SelectProvider() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectProvider")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectProvider indicates an expected call of SelectProvider.
func (mr *MockEmbeddedResourceMockRecorder) SelectProvider() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectProvider", reflect.TypeOf((*MockEmbeddedResource)(nil).SelectProvider))
}
