// Code generated by MockGen. DO NOT EDIT.
// Source: regpublisher/nats.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source regpublisher/nats.go -destination regpublisher/publisher_mock_test.go -package regpublisher NatsMessagePublisher,JetStreamMessagePublisher
//

// Package regpublisher is a generated GoMock package.
package regpublisher

import (
	context "context"
	reflect "reflect"

	nats "github.com/nats-io/nats.go"
	jetstream "github.com/nats-io/nats.go/jetstream"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source regpublisher/nats.go -destination regpublisher/publisher_mock_test.go -package regpublisher NatsMessagePublisher,JetStreamMessagePublisher

// MockNatsMessagePublisher is a mock of NatsMessagePublisher interface.
type MockNatsMessagePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockNatsMessagePublisherMockRecorder
	isgomock struct{}
}

// MockNatsMessagePublisherMockRecorder is the mock recorder for MockNatsMessagePublisher.
type MockNatsMessagePublisherMockRecorder struct {
	mock *MockNatsMessagePublisher
}

// NewMockNatsMessagePublisher creates a new mock instance.
func NewMockNatsMessagePublisher(ctrl *gomock.Controller) *MockNatsMessagePublisher {
	mock := &MockNatsMessagePublisher{ctrl: ctrl}
	mock.recorder = &MockNatsMessagePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNatsMessagePublisher) EXPECT() *MockNatsMessagePublisherMockRecorder {
	return m.recorder
}

// PublishMsg mocks base method.
func (m *MockNatsMessagePublisher) PublishMsg(msg *nats.Msg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMsg", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishMsg indicates an expected call of PublishMsg.
func (mr *MockNatsMessagePublisherMockRecorder) PublishMsg(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMsg", reflect.TypeOf((*MockNatsMessagePublisher)(nil).PublishMsg), msg)
}

// MockJetStreamMessagePublisher is a mock of JetStreamMessagePublisher interface.
type MockJetStreamMessagePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockJetStreamMessagePublisherMockRecorder
	isgomock struct{}
}

// MockJetStreamMessagePublisherMockRecorder is the mock recorder for MockJetStreamMessagePublisher.
type MockJetStreamMessagePublisherMockRecorder struct {
	mock *MockJetStreamMessagePublisher
}

// NewMockJetStreamMessagePublisher creates a new mock instance.
func NewMockJetStreamMessagePublisher(ctrl *gomock.Controller) *MockJetStreamMessagePublisher {
	mock := &MockJetStreamMessagePublisher{ctrl: ctrl}
	mock.recorder = &MockJetStreamMessagePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJetStreamMessagePublisher) EXPECT() *MockJetStreamMessagePublisherMockRecorder {
	return m.recorder
}

// PublishMsg mocks base method.
func (m *MockJetStreamMessagePublisher) PublishMsg(ctx context.Context, msg *nats.Msg, opts ...jetstream.PublishOpt) (*jetstream.PubAck, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PublishMsg", varargs...)
	ret0, _ := ret[0].(*jetstream.PubAck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishMsg indicates an expected call of PublishMsg.
func (mr *MockJetStreamMessagePublisherMockRecorder) PublishMsg(ctx, msg any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMsg", reflect.TypeOf((*MockJetStreamMessagePublisher)(nil).PublishMsg), varargs...)
}
