// Code generated by MockGen. DO NOT EDIT.
// Source: resources/exec/exec.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source resources/exec/exec.go -destination resources/exec/provider_mock_test.go -package execresource
//

// Package execresource is a generated GoMock package.
package execresource

import (
	context "context"
	reflect "reflect"

	model "github.com/choria-io/ccm/model"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source resources/exec/exec.go -destination resources/exec/provider_mock_test.go -package execresource

// MockExecProvider is a mock of ExecProvider interface.
type MockExecProvider struct {
	ctrl     *gomock.Controller
	recorder *MockExecProviderMockRecorder
	isgomock struct{}
}

// MockExecProviderMockRecorder is the mock recorder for MockExecProvider.
type MockExecProviderMockRecorder struct {
	mock *MockExecProvider
}

// NewMockExecProvider creates a new mock instance.
func NewMockExecProvider(ctrl *gomock.Controller) *MockExecProvider {
	mock := &MockExecProvider{ctrl: ctrl}
	mock.recorder = &MockExecProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecProvider) EXPECT() *MockExecProviderMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockExecProvider) Execute(ctx context.Context, properties *model.ExecResourceProperties, log model.Logger) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, properties, log)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockExecProviderMockRecorder) Execute(ctx, properties, log any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExecProvider)(nil).Execute), ctx, properties, log)
}

// Name mocks base method.
func (m *MockExecProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockExecProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockExecProvider)(nil).Name))
}

// Status mocks base method.
func (m *MockExecProvider) Status(ctx context.Context, properties *model.ExecResourceProperties) (*model.ExecState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, properties)
	ret0, _ := ret[0].(*model.ExecState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockExecProviderMockRecorder) Status(ctx, properties any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockExecProvider)(nil).Status), ctx, properties)
}
