// Code generated by MockGen. DO NOT EDIT.
// Source: registration/nats.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source registration/nats.go -destination registration/publisher_mock_test.go -package registration natsMessagePublisher,jetStreamMessagePublisher
//

// Package registration is a generated GoMock package.
package registration

import (
	context "context"
	reflect "reflect"

	nats "github.com/nats-io/nats.go"
	jetstream "github.com/nats-io/nats.go/jetstream"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source registration/nats.go -destination registration/publisher_mock_test.go -package registration natsMessagePublisher,jetStreamMessagePublisher

// MocknatsMessagePublisher is a mock of natsMessagePublisher interface.
type MocknatsMessagePublisher struct {
	ctrl     *gomock.Controller
	recorder *MocknatsMessagePublisherMockRecorder
	isgomock struct{}
}

// MocknatsMessagePublisherMockRecorder is the mock recorder for MocknatsMessagePublisher.
type MocknatsMessagePublisherMockRecorder struct {
	mock *MocknatsMessagePublisher
}

// NewMocknatsMessagePublisher creates a new mock instance.
func NewMocknatsMessagePublisher(ctrl *gomock.Controller) *MocknatsMessagePublisher {
	mock := &MocknatsMessagePublisher{ctrl: ctrl}
	mock.recorder = &MocknatsMessagePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocknatsMessagePublisher) EXPECT() *MocknatsMessagePublisherMockRecorder {
	return m.recorder
}

// PublishMsg mocks base method.
func (m *MocknatsMessagePublisher) PublishMsg(msg *nats.Msg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMsg", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishMsg indicates an expected call of PublishMsg.
func (mr *MocknatsMessagePublisherMockRecorder) PublishMsg(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMsg", reflect.TypeOf((*MocknatsMessagePublisher)(nil).PublishMsg), msg)
}

// MockjetStreamMessagePublisher is a mock of jetStreamMessagePublisher interface.
type MockjetStreamMessagePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockjetStreamMessagePublisherMockRecorder
	isgomock struct{}
}

// MockjetStreamMessagePublisherMockRecorder is the mock recorder for MockjetStreamMessagePublisher.
type MockjetStreamMessagePublisherMockRecorder struct {
	mock *MockjetStreamMessagePublisher
}

// NewMockjetStreamMessagePublisher creates a new mock instance.
func NewMockjetStreamMessagePublisher(ctrl *gomock.Controller) *MockjetStreamMessagePublisher {
	mock := &MockjetStreamMessagePublisher{ctrl: ctrl}
	mock.recorder = &MockjetStreamMessagePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjetStreamMessagePublisher) EXPECT() *MockjetStreamMessagePublisherMockRecorder {
	return m.recorder
}

// PublishMsg mocks base method.
func (m *MockjetStreamMessagePublisher) PublishMsg(ctx context.Context, msg *nats.Msg, opts ...jetstream.PublishOpt) (*jetstream.PubAck, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, msg}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PublishMsg", varargs...)
	ret0, _ := ret[0].(*jetstream.PubAck)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishMsg indicates an expected call of PublishMsg.
func (mr *MockjetStreamMessagePublisherMockRecorder) PublishMsg(ctx, msg any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, msg}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMsg", reflect.TypeOf((*MockjetStreamMessagePublisher)(nil).PublishMsg), varargs...)
}
