// Code generated by MockGen. DO NOT EDIT.
// Source: model/manager.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source model/manager.go -destination model/modelmocks/manage_mock.go -package modelmocks
//

// Package modelmocks is a generated GoMock package.
package modelmocks

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	model "github.com/choria-io/ccm/model"
	templates "github.com/choria-io/ccm/templates"
	nats "github.com/nats-io/nats.go"
	jetstream "github.com/nats-io/nats.go/jetstream"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source model/manager.go -destination model/modelmocks/manage_mock.go -package modelmocks

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), varargs...)
}

// Error mocks base method.
func (m *MockLogger) Error(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), varargs...)
}

// Info mocks base method.
func (m *MockLogger) Info(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), varargs...)
}

// Warn mocks base method.
func (m *MockLogger) Warn(msg string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{msg}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Warn", varargs...)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(msg any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{msg}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), varargs...)
}

// With mocks base method.
func (m *MockLogger) With(args ...any) model.Logger {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "With", varargs...)
	ret0, _ := ret[0].(model.Logger)
	return ret0
}

// With indicates an expected call of With.
func (mr *MockLoggerMockRecorder) With(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "With", reflect.TypeOf((*MockLogger)(nil).With), args...)
}

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockManager) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockManagerMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockManager)(nil).Close))
}

// Data mocks base method.
func (m *MockManager) Data() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Data")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// Data indicates an expected call of Data.
func (mr *MockManagerMockRecorder) Data() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Data", reflect.TypeOf((*MockManager)(nil).Data))
}

// Facts mocks base method.
func (m *MockManager) Facts(ctx context.Context) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Facts", ctx)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Facts indicates an expected call of Facts.
func (mr *MockManagerMockRecorder) Facts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Facts", reflect.TypeOf((*MockManager)(nil).Facts), ctx)
}

// FactsRaw mocks base method.
func (m *MockManager) FactsRaw(ctx context.Context) (json.RawMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FactsRaw", ctx)
	ret0, _ := ret[0].(json.RawMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FactsRaw indicates an expected call of FactsRaw.
func (mr *MockManagerMockRecorder) FactsRaw(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FactsRaw", reflect.TypeOf((*MockManager)(nil).FactsRaw), ctx)
}

// IsResourceFailed mocks base method.
func (m *MockManager) IsResourceFailed(resourceType, resourceName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsResourceFailed", resourceType, resourceName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsResourceFailed indicates an expected call of IsResourceFailed.
func (mr *MockManagerMockRecorder) IsResourceFailed(resourceType, resourceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsResourceFailed", reflect.TypeOf((*MockManager)(nil).IsResourceFailed), resourceType, resourceName)
}

// JetStream mocks base method.
func (m *MockManager) JetStream() (jetstream.JetStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JetStream")
	ret0, _ := ret[0].(jetstream.JetStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// JetStream indicates an expected call of JetStream.
func (mr *MockManagerMockRecorder) JetStream() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JetStream", reflect.TypeOf((*MockManager)(nil).JetStream))
}

// Logger mocks base method.
func (m *MockManager) Logger(args ...any) (model.Logger, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Logger", varargs...)
	ret0, _ := ret[0].(model.Logger)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Logger indicates an expected call of Logger.
func (mr *MockManagerMockRecorder) Logger(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockManager)(nil).Logger), args...)
}

// MergeFacts mocks base method.
func (m *MockManager) MergeFacts(ctx context.Context, facts map[string]any) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergeFacts", ctx, facts)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergeFacts indicates an expected call of MergeFacts.
func (mr *MockManagerMockRecorder) MergeFacts(ctx, facts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergeFacts", reflect.TypeOf((*MockManager)(nil).MergeFacts), ctx, facts)
}

// NewRunner mocks base method.
func (m *MockManager) NewRunner() (model.CommandRunner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewRunner")
	ret0, _ := ret[0].(model.CommandRunner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewRunner indicates an expected call of NewRunner.
func (mr *MockManagerMockRecorder) NewRunner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewRunner", reflect.TypeOf((*MockManager)(nil).NewRunner))
}

// NoopMode mocks base method.
func (m *MockManager) NoopMode() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NoopMode")
	ret0, _ := ret[0].(bool)
	return ret0
}

// NoopMode indicates an expected call of NoopMode.
func (mr *MockManagerMockRecorder) NoopMode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoopMode", reflect.TypeOf((*MockManager)(nil).NoopMode))
}

// RecordEvent mocks base method.
func (m *MockManager) RecordEvent(event *model.TransactionEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordEvent", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordEvent indicates an expected call of RecordEvent.
func (mr *MockManagerMockRecorder) RecordEvent(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordEvent", reflect.TypeOf((*MockManager)(nil).RecordEvent), event)
}

// ResourceInfo mocks base method.
func (m *MockManager) ResourceInfo(ctx context.Context, typeName, name string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResourceInfo", ctx, typeName, name)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResourceInfo indicates an expected call of ResourceInfo.
func (mr *MockManagerMockRecorder) ResourceInfo(ctx, typeName, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResourceInfo", reflect.TypeOf((*MockManager)(nil).ResourceInfo), ctx, typeName, name)
}

// SessionSummary mocks base method.
func (m *MockManager) SessionSummary() (*model.SessionSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionSummary")
	ret0, _ := ret[0].(*model.SessionSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SessionSummary indicates an expected call of SessionSummary.
func (mr *MockManagerMockRecorder) SessionSummary() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionSummary", reflect.TypeOf((*MockManager)(nil).SessionSummary))
}

// SetData mocks base method.
func (m *MockManager) SetData(data map[string]any) map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetData", data)
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// SetData indicates an expected call of SetData.
func (mr *MockManagerMockRecorder) SetData(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetData", reflect.TypeOf((*MockManager)(nil).SetData), data)
}

// SetExternalData mocks base method.
func (m *MockManager) SetExternalData(data map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetExternalData", data)
}

// SetExternalData indicates an expected call of SetExternalData.
func (mr *MockManagerMockRecorder) SetExternalData(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExternalData", reflect.TypeOf((*MockManager)(nil).SetExternalData), data)
}

// SetFacts mocks base method.
func (m *MockManager) SetFacts(facts map[string]any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFacts", facts)
}

// SetFacts indicates an expected call of SetFacts.
func (mr *MockManagerMockRecorder) SetFacts(facts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFacts", reflect.TypeOf((*MockManager)(nil).SetFacts), facts)
}

// SetWorkingDirectory mocks base method.
func (m *MockManager) SetWorkingDirectory(dir string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetWorkingDirectory", dir)
}

// SetWorkingDirectory indicates an expected call of SetWorkingDirectory.
func (mr *MockManagerMockRecorder) SetWorkingDirectory(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWorkingDirectory", reflect.TypeOf((*MockManager)(nil).SetWorkingDirectory), dir)
}

// ShouldRefresh mocks base method.
func (m *MockManager) ShouldRefresh(resourceType, resourceName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldRefresh", resourceType, resourceName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShouldRefresh indicates an expected call of ShouldRefresh.
func (mr *MockManagerMockRecorder) ShouldRefresh(resourceType, resourceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldRefresh", reflect.TypeOf((*MockManager)(nil).ShouldRefresh), resourceType, resourceName)
}

// StartSession mocks base method.
func (m *MockManager) StartSession(arg0 model.Apply) (model.SessionStore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSession", arg0)
	ret0, _ := ret[0].(model.SessionStore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartSession indicates an expected call of StartSession.
func (mr *MockManagerMockRecorder) StartSession(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSession", reflect.TypeOf((*MockManager)(nil).StartSession), arg0)
}

// SystemFacts mocks base method.
func (m *MockManager) SystemFacts(ctx context.Context) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SystemFacts", ctx)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SystemFacts indicates an expected call of SystemFacts.
func (mr *MockManagerMockRecorder) SystemFacts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SystemFacts", reflect.TypeOf((*MockManager)(nil).SystemFacts), ctx)
}

// TemplateEnvironment mocks base method.
func (m *MockManager) TemplateEnvironment(ctx context.Context) (*templates.Env, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TemplateEnvironment", ctx)
	ret0, _ := ret[0].(*templates.Env)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TemplateEnvironment indicates an expected call of TemplateEnvironment.
func (mr *MockManagerMockRecorder) TemplateEnvironment(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TemplateEnvironment", reflect.TypeOf((*MockManager)(nil).TemplateEnvironment), ctx)
}

// UserLogger mocks base method.
func (m *MockManager) UserLogger() model.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserLogger")
	ret0, _ := ret[0].(model.Logger)
	return ret0
}

// UserLogger indicates an expected call of UserLogger.
func (mr *MockManagerMockRecorder) UserLogger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserLogger", reflect.TypeOf((*MockManager)(nil).UserLogger))
}

// WorkingDirectory mocks base method.
func (m *MockManager) WorkingDirectory() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WorkingDirectory")
	ret0, _ := ret[0].(string)
	return ret0
}

// WorkingDirectory indicates an expected call of WorkingDirectory.
func (mr *MockManagerMockRecorder) WorkingDirectory() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WorkingDirectory", reflect.TypeOf((*MockManager)(nil).WorkingDirectory))
}

// MockNatsConnProvider is a mock of NatsConnProvider interface.
type MockNatsConnProvider struct {
	ctrl     *gomock.Controller
	recorder *MockNatsConnProviderMockRecorder
	isgomock struct{}
}

// MockNatsConnProviderMockRecorder is the mock recorder for MockNatsConnProvider.
type MockNatsConnProviderMockRecorder struct {
	mock *MockNatsConnProvider
}

// NewMockNatsConnProvider creates a new mock instance.
func NewMockNatsConnProvider(ctrl *gomock.Controller) *MockNatsConnProvider {
	mock := &MockNatsConnProvider{ctrl: ctrl}
	mock.recorder = &MockNatsConnProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNatsConnProvider) EXPECT() *MockNatsConnProviderMockRecorder {
	return m.recorder
}

// Connect mocks base method.
func (m *MockNatsConnProvider) Connect(natsContext string, opts ...nats.Option) (*nats.Conn, error) {
	m.ctrl.T.Helper()
	varargs := []any{natsContext}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Connect", varargs...)
	ret0, _ := ret[0].(*nats.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Connect indicates an expected call of Connect.
func (mr *MockNatsConnProviderMockRecorder) Connect(natsContext any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{natsContext}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connect", reflect.TypeOf((*MockNatsConnProvider)(nil).Connect), varargs...)
}
