// Code generated by MockGen. DO NOT EDIT.
// Source: model/provider.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source model/provider.go -destination model/modelmocks/provider_mock.go -package modelmocks
//

// Package modelmocks is a generated GoMock package.
package modelmocks

import (
	reflect "reflect"

	model "github.com/choria-io/ccm/model"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source model/provider.go -destination model/modelmocks/provider_mock.go -package modelmocks

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockProvider)(nil).Name))
}

// MockProviderFactory is a mock of ProviderFactory interface.
type MockProviderFactory struct {
	ctrl     *gomock.Controller
	recorder *MockProviderFactoryMockRecorder
	isgomock struct{}
}

// MockProviderFactoryMockRecorder is the mock recorder for MockProviderFactory.
type MockProviderFactoryMockRecorder struct {
	mock *MockProviderFactory
}

// NewMockProviderFactory creates a new mock instance.
func NewMockProviderFactory(ctrl *gomock.Controller) *MockProviderFactory {
	mock := &MockProviderFactory{ctrl: ctrl}
	mock.recorder = &MockProviderFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProviderFactory) EXPECT() *MockProviderFactoryMockRecorder {
	return m.recorder
}

// IsManageable mocks base method.
func (m *MockProviderFactory) IsManageable(arg0 map[string]any) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsManageable", arg0)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsManageable indicates an expected call of IsManageable.
func (mr *MockProviderFactoryMockRecorder) IsManageable(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsManageable", reflect.TypeOf((*MockProviderFactory)(nil).IsManageable), arg0)
}

// Name mocks base method.
func (m *MockProviderFactory) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockProviderFactoryMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockProviderFactory)(nil).Name))
}

// New mocks base method.
func (m *MockProviderFactory) New(arg0 model.Logger, arg1 model.CommandRunner) (model.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "New", arg0, arg1)
	ret0, _ := ret[0].(model.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockProviderFactoryMockRecorder) New(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockProviderFactory)(nil).New), arg0, arg1)
}

// TypeName mocks base method.
func (m *MockProviderFactory) TypeName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TypeName")
	ret0, _ := ret[0].(string)
	return ret0
}

// TypeName indicates an expected call of TypeName.
func (mr *MockProviderFactoryMockRecorder) TypeName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TypeName", reflect.TypeOf((*MockProviderFactory)(nil).TypeName))
}
