// Code generated by MockGen. DO NOT EDIT.
// Source: model/registration.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source model/registration.go -destination model/modelmocks/registration_mock.go -package modelmocks
//

// Package modelmocks is a generated GoMock package.
package modelmocks

import (
	context "context"
	reflect "reflect"

	model "github.com/choria-io/ccm/model"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source model/registration.go -destination model/modelmocks/registration_mock.go -package modelmocks

// MockRegistrationPublisher is a mock of RegistrationPublisher interface.
type MockRegistrationPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockRegistrationPublisherMockRecorder
	isgomock struct{}
}

// MockRegistrationPublisherMockRecorder is the mock recorder for MockRegistrationPublisher.
type MockRegistrationPublisherMockRecorder struct {
	mock *MockRegistrationPublisher
}

// NewMockRegistrationPublisher creates a new mock instance.
func NewMockRegistrationPublisher(ctrl *gomock.Controller) *MockRegistrationPublisher {
	mock := &MockRegistrationPublisher{ctrl: ctrl}
	mock.recorder = &MockRegistrationPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistrationPublisher) EXPECT() *MockRegistrationPublisherMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockRegistrationPublisher) Publish(ctx context.Context, entry *model.RegistrationEntry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockRegistrationPublisherMockRecorder) Publish(ctx, entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockRegistrationPublisher)(nil).Publish), ctx, entry)
}
