// Code generated by MockGen. DO NOT EDIT.
// Source: model/runner.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source model/runner.go -destination model/modelmocks/runner_mock.go -package modelmocks
//

// Package modelmocks is a generated GoMock package.
package modelmocks

import (
	context "context"
	reflect "reflect"

	model "github.com/choria-io/ccm/model"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source model/runner.go -destination model/modelmocks/runner_mock.go -package modelmocks

// MockCommandRunner is a mock of CommandRunner interface.
type MockCommandRunner struct {
	ctrl     *gomock.Controller
	recorder *MockCommandRunnerMockRecorder
	isgomock struct{}
}

// MockCommandRunnerMockRecorder is the mock recorder for MockCommandRunner.
type MockCommandRunnerMockRecorder struct {
	mock *MockCommandRunner
}

// NewMockCommandRunner creates a new mock instance.
func NewMockCommandRunner(ctrl *gomock.Controller) *MockCommandRunner {
	mock := &MockCommandRunner{ctrl: ctrl}
	mock.recorder = &MockCommandRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandRunner) EXPECT() *MockCommandRunnerMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCommandRunner) Execute(ctx context.Context, cmd string, args ...string) ([]byte, []byte, int, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, cmd}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Execute", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Execute indicates an expected call of Execute.
func (mr *MockCommandRunnerMockRecorder) Execute(ctx, cmd any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, cmd}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCommandRunner)(nil).Execute), varargs...)
}

// ExecuteWithOptions mocks base method.
func (m *MockCommandRunner) ExecuteWithOptions(ctx context.Context, opts model.ExtendedExecOptions) ([]byte, []byte, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteWithOptions", ctx, opts)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ExecuteWithOptions indicates an expected call of ExecuteWithOptions.
func (mr *MockCommandRunnerMockRecorder) ExecuteWithOptions(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteWithOptions", reflect.TypeOf((*MockCommandRunner)(nil).ExecuteWithOptions), ctx, opts)
}
