// Code generated by MockGen. DO NOT EDIT.
// Source: transaction.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source transaction.go -destination modelmocks/transaction_mock.go -package modelmocks
//

// Package modelmocks is a generated GoMock package.
package modelmocks

import (
	reflect "reflect"

	model "github.com/choria-io/ccm/model"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source transaction.go -destination modelmocks/transaction_mock.go -package modelmocks

// MockSessionEvent is a mock of SessionEvent interface.
type MockSessionEvent struct {
	ctrl     *gomock.Controller
	recorder *MockSessionEventMockRecorder
	isgomock struct{}
}

// MockSessionEventMockRecorder is the mock recorder for MockSessionEvent.
type MockSessionEventMockRecorder struct {
	mock *MockSessionEvent
}

// NewMockSessionEvent creates a new mock instance.
func NewMockSessionEvent(ctrl *gomock.Controller) *MockSessionEvent {
	mock := &MockSessionEvent{ctrl: ctrl}
	mock.recorder = &MockSessionEventMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionEvent) EXPECT() *MockSessionEventMockRecorder {
	return m.recorder
}

// SessionEventID mocks base method.
func (m *MockSessionEvent) SessionEventID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SessionEventID")
	ret0, _ := ret[0].(string)
	return ret0
}

// SessionEventID indicates an expected call of SessionEventID.
func (mr *MockSessionEventMockRecorder) SessionEventID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionEventID", reflect.TypeOf((*MockSessionEvent)(nil).SessionEventID))
}

// String mocks base method.
func (m *MockSessionEvent) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockSessionEventMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockSessionEvent)(nil).String))
}

// MockApply is a mock of Apply interface.
type MockApply struct {
	ctrl     *gomock.Controller
	recorder *MockApplyMockRecorder
	isgomock struct{}
}

// MockApplyMockRecorder is the mock recorder for MockApply.
type MockApplyMockRecorder struct {
	mock *MockApply
}

// NewMockApply creates a new mock instance.
func NewMockApply(ctrl *gomock.Controller) *MockApply {
	mock := &MockApply{ctrl: ctrl}
	mock.recorder = &MockApplyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApply) EXPECT() *MockApplyMockRecorder {
	return m.recorder
}

// Data mocks base method.
func (m *MockApply) Data() map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Data")
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// Data indicates an expected call of Data.
func (mr *MockApplyMockRecorder) Data() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Data", reflect.TypeOf((*MockApply)(nil).Data))
}

// Resources mocks base method.
func (m *MockApply) Resources() []map[string]model.ResourceProperties {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resources")
	ret0, _ := ret[0].([]map[string]model.ResourceProperties)
	return ret0
}

// Resources indicates an expected call of Resources.
func (mr *MockApplyMockRecorder) Resources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resources", reflect.TypeOf((*MockApply)(nil).Resources))
}

// MockSessionStore is a mock of SessionStore interface.
type MockSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockSessionStoreMockRecorder
	isgomock struct{}
}

// MockSessionStoreMockRecorder is the mock recorder for MockSessionStore.
type MockSessionStoreMockRecorder struct {
	mock *MockSessionStore
}

// NewMockSessionStore creates a new mock instance.
func NewMockSessionStore(ctrl *gomock.Controller) *MockSessionStore {
	mock := &MockSessionStore{ctrl: ctrl}
	mock.recorder = &MockSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionStore) EXPECT() *MockSessionStoreMockRecorder {
	return m.recorder
}

// AllEvents mocks base method.
func (m *MockSessionStore) AllEvents() ([]model.SessionEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllEvents")
	ret0, _ := ret[0].([]model.SessionEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AllEvents indicates an expected call of AllEvents.
func (mr *MockSessionStoreMockRecorder) AllEvents() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllEvents", reflect.TypeOf((*MockSessionStore)(nil).AllEvents))
}

// EventsForResource mocks base method.
func (m *MockSessionStore) EventsForResource(resourceType, resourceName string) ([]model.TransactionEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventsForResource", resourceType, resourceName)
	ret0, _ := ret[0].([]model.TransactionEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventsForResource indicates an expected call of EventsForResource.
func (mr *MockSessionStoreMockRecorder) EventsForResource(resourceType, resourceName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventsForResource", reflect.TypeOf((*MockSessionStore)(nil).EventsForResource), resourceType, resourceName)
}

// RecordEvent mocks base method.
func (m *MockSessionStore) RecordEvent(arg0 model.SessionEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordEvent", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordEvent indicates an expected call of RecordEvent.
func (mr *MockSessionStoreMockRecorder) RecordEvent(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordEvent", reflect.TypeOf((*MockSessionStore)(nil).RecordEvent), arg0)
}

// StartSession mocks base method.
func (m *MockSessionStore) StartSession(arg0 model.Apply) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSession", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartSession indicates an expected call of StartSession.
func (mr *MockSessionStoreMockRecorder) StartSession(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSession", reflect.TypeOf((*MockSessionStore)(nil).StartSession), arg0)
}

// StopSession mocks base method.
func (m *MockSessionStore) StopSession(destroy bool) (*model.SessionSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopSession", destroy)
	ret0, _ := ret[0].(*model.SessionSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopSession indicates an expected call of StopSession.
func (mr *MockSessionStoreMockRecorder) StopSession(destroy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopSession", reflect.TypeOf((*MockSessionStore)(nil).StopSession), destroy)
}
