// Code generated by MockGen. DO NOT EDIT.
// Source: package.go
//
// Generated by this command:
//
//	mockgen -write_generate_directive -source package.go -destination provider_mock_test.go -package packageresource
//

// Package packageresource is a generated GoMock package.
package packageresource

import (
	context "context"
	reflect "reflect"

	model "github.com/choria-io/ccm/model"
	gomock "go.uber.org/mock/gomock"
)

//go:generate mockgen -write_generate_directive -source package.go -destination provider_mock_test.go -package packageresource

// MockPackageProvider is a mock of PackageProvider interface.
type MockPackageProvider struct {
	ctrl     *gomock.Controller
	recorder *MockPackageProviderMockRecorder
	isgomock struct{}
}

// MockPackageProviderMockRecorder is the mock recorder for MockPackageProvider.
type MockPackageProviderMockRecorder struct {
	mock *MockPackageProvider
}

// NewMockPackageProvider creates a new mock instance.
func NewMockPackageProvider(ctrl *gomock.Controller) *MockPackageProvider {
	mock := &MockPackageProvider{ctrl: ctrl}
	mock.recorder = &MockPackageProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPackageProvider) EXPECT() *MockPackageProviderMockRecorder {
	return m.recorder
}

// Downgrade mocks base method.
func (m *MockPackageProvider) Downgrade(ctx context.Context, pkg, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Downgrade", ctx, pkg, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// Downgrade indicates an expected call of Downgrade.
func (mr *MockPackageProviderMockRecorder) Downgrade(ctx, pkg, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Downgrade", reflect.TypeOf((*MockPackageProvider)(nil).Downgrade), ctx, pkg, version)
}

// Install mocks base method.
func (m *MockPackageProvider) Install(ctx context.Context, pkg, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Install", ctx, pkg, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// Install indicates an expected call of Install.
func (mr *MockPackageProviderMockRecorder) Install(ctx, pkg, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Install", reflect.TypeOf((*MockPackageProvider)(nil).Install), ctx, pkg, version)
}

// Name mocks base method.
func (m *MockPackageProvider) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockPackageProviderMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockPackageProvider)(nil).Name))
}

// Status mocks base method.
func (m *MockPackageProvider) Status(ctx context.Context, pkg string) (*model.PackageState, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status", ctx, pkg)
	ret0, _ := ret[0].(*model.PackageState)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status.
func (mr *MockPackageProviderMockRecorder) Status(ctx, pkg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockPackageProvider)(nil).Status), ctx, pkg)
}

// Uninstall mocks base method.
func (m *MockPackageProvider) Uninstall(ctx context.Context, pkg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Uninstall", ctx, pkg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Uninstall indicates an expected call of Uninstall.
func (mr *MockPackageProviderMockRecorder) Uninstall(ctx, pkg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Uninstall", reflect.TypeOf((*MockPackageProvider)(nil).Uninstall), ctx, pkg)
}

// Upgrade mocks base method.
func (m *MockPackageProvider) Upgrade(ctx context.Context, pkg, version string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upgrade", ctx, pkg, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upgrade indicates an expected call of Upgrade.
func (mr *MockPackageProviderMockRecorder) Upgrade(ctx, pkg, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upgrade", reflect.TypeOf((*MockPackageProvider)(nil).Upgrade), ctx, pkg, version)
}
